[build]
  builder = "nixpacks"
  buildCommand = "npx prisma generate && npm run build"
  startCommand = "npx prisma db push && npm start"

[deploy]
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
